/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { TestIDefenDAO, TestIDefenDAOInterface } from "../TestIDefenDAO";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "nftAddress_",
        type: "address",
      },
      {
        internalType: "address",
        name: "marketplaceAddress_",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "curFloorPrice_",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "offerPriceUnit_",
        type: "uint256",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "mockRecordRecentSold",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class TestIDefenDAO__factory {
  static readonly abi = _abi;
  static createInterface(): TestIDefenDAOInterface {
    return new utils.Interface(_abi) as TestIDefenDAOInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TestIDefenDAO {
    return new Contract(address, _abi, signerOrProvider) as TestIDefenDAO;
  }
}
